"""
ChordRealizer: Expands chord symbols into a dense, continuous stream of
note_events to prevent modal collapse during autoregressive generation.

SYMPHONIC MODE ADDITIONS:
- `_bar_range` now takes `beats_per_bar` (read from the section dict, default
  4) instead of hardcoding `// 4`, so density-curve windowing lines up
  correctly under 3/4, 6/8, etc.
- Harmony voices no longer double the *entire* chord in unison. Previously,
  every instrument assigned the "harmony" role independently played the
  same stacked voicing (all four chord tones, same octave) every beat — a
  choir and a string section given "harmony" would play identical pitches
  at identical times, just with different timbre. Now, when a section has
  2+ harmony-role instruments, each is assigned ONE chord tone plus a
  register offset based on its voice index (`_harmony_index`), so the
  chord is spread across parts the way real divisi strings or SATB voicing
  works: voice 0 (first harmony instrument — typically the most prominent,
  e.g. first violins) takes the highest listed tone; later voices step down
  in both tone and octave register. A section with exactly one harmony
  instrument keeps the old full-stack-sustain behavior, since a lone
  piano/pad carrying the whole voicing is still the right call there.
- EXPLICIT MELODY: when a section carries a `melody_pattern` (built by
  StructurePlanner from a user-supplied explicit_melody token list), the
  lead voice's algorithmic density-driven line is skipped entirely and
  replaced with the user's own notes, decoupled from the chord grid.
- PHRASE MELODY GENERATION: when no explicit melody was given, the lead
  voice is no longer generated by per-chord tone-cycling. `_generate_phrase_
  melody` builds a rule-based (NOT neural) melodic line with real phrase
  structure instead: chord tones on strong beats for harmonic stability,
  passing scale tones on weak beats for melodic interest, organized into
  repeating phrases with a contour shape (arch/ascend/descend, or a short
  repeating riff/ostinato when riff mode is on) chosen from the section's
  energy_curve, using one rhythmic motif generated once and reused across
  phrases for cohesion instead of resampling rhythm independently every bar.
- SOLOS: when a section has a solo_instrument set, that instrument is
  already moved to the "lead" role by StructurePlanner (index 0), so it
  gets the full phrase-melody treatment automatically; ChordRealizer's own
  job here is just to thin the OTHER (harmony) voices so the soloist has
  room — fewer stacked tones, fewer active voices, sparser rhythm.
"""
import logging
from typing import List, Dict, Any, Optional
from shared.gm_instruments import get_program, infer_role, default_octave_for_role, DRUM_PROGRAM
from shared.music_theory_constants import NOTE_MAP, SCALE_MODES

logger = logging.getLogger(__name__)

_QUALITY_INTERVALS = [
    # Longest/most-specific tokens first, deliberately — substring matching
    # is fragile against short generic tokens like "m"/"7" matching inside
    # longer quality strings, so anything ambiguous needs to be caught
    # before it reaches them.
    ("maj9", [0, 4, 7, 11, 2]), ("maj7", [0, 4, 7, 11]),
    ("m7b5", [0, 3, 6, 10]), ("dim7", [0, 3, 6, 9]), ("dim", [0, 3, 6]),
    ("min9", [0, 3, 7, 10, 2]), ("m9", [0, 3, 7, 10, 2]),
    ("min7", [0, 3, 7, 10]), ("m7", [0, 3, 7, 10]),
    ("madd9", [0, 3, 7, 2]), ("add9", [0, 4, 7, 2]),
    ("13", [0, 4, 7, 10, 2, 9]), ("11", [0, 4, 7, 10, 2, 5]), ("9", [0, 4, 7, 10, 2]),
    ("7sus4", [0, 5, 7, 10]), ("7sus2", [0, 2, 7, 10]),
    ("sus4", [0, 5, 7]), ("sus2", [0, 2, 7]),
    ("7", [0, 4, 7, 10]),
    ("aug", [0, 4, 8]),
    ("min", [0, 3, 7]), ("m", [0, 3, 7]),
]
_DEFAULT_MAJOR_TRIAD = [0, 4, 7]

def _chord_tones(quality: str) -> List[int]:
    q = (quality or "").strip().lower()
    # BUGFIX: "maj" (and "") used to fall through to the generic substring
    # scan below, where the "m" token matches — "m" IS a substring of
    # "maj" — silently returning the MINOR triad for every plain major
    # chord (e.g. explicit_chords entries like "Bb", "F", "C" with no
    # suffix, which StructurePlanner._parse_explicit_chord normalizes to
    # quality "maj"). This exact-match guard has to run BEFORE the
    # substring loop, not be folded into it, or the collision comes right
    # back. Also covers "Cmaj"-style user input directly.
    if q in ("", "maj", "major"):
        return _DEFAULT_MAJOR_TRIAD
    for token, intervals in _QUALITY_INTERVALS:
        if token in q: return intervals
    return _DEFAULT_MAJOR_TRIAD


# ---------------------------------------------------------------------
# PHRASE MELODY GENERATION (rule-based, NOT a neural model)
# ---------------------------------------------------------------------
# Contour templates are sequences of scale-degree offsets from a phrase's
# starting degree. "riff" is intentionally short (a 4-note cell meant to
# repeat) while the others span a full phrase length before repeating with
# a shifted starting degree.
_CONTOUR_TEMPLATES = {
    "arch":    [0, 1, 2, 3, 4, 3, 2, 1],
    "ascend":  [0, 1, 2, 3, 4, 5, 6, 7],
    "descend": [0, -1, -2, -3, -4, -5, -6, -7],
    "riff":    [0, 2, 4, 2],
}
_ENERGY_TO_CONTOUR = {"build": "arch", "fade": "descend", "flat": "arch"}


class ChordRealizer:
    def __init__(self, octave_vocab_size: int = 9, pitch_class_vocab_size: int = 12, instrument_vocab_size: int = 130):
        self.max_octave = max(0, octave_vocab_size - 3)
        self.max_pitch_class = max(0, pitch_class_vocab_size - 3)
        self.max_instrument = max(0, instrument_vocab_size - 3)

    def _generate_phrase_melody(self, progression: List[Dict], bars: int, beats_per_bar: int,
                                 density_curve: List[float], mood: str, energy_curve: str,
                                 key: str, mode: str, riff: bool = False) -> List[Dict[str, Any]]:
        """
        Rule-based phrase melody generator. This is NOT a neural model —
        it's a deterministic heuristic that gives the lead voice real
        musical structure instead of the old behavior (independently
        cycling through chord tones every subdivision with no sense of
        phrase, contour, or motif). Design:
        - Notes come from the section's actual scale (SCALE_MODES for its
          key/mode), not just the current chord's triad — chord tones are
          used on strong (on-the-beat) positions for harmonic stability;
          off-beat positions are free to use passing scale tones for
          melodic interest. Standard classical melody-writing heuristic.
        - The melody is organized into repeating phrases (2 bars each) with
          a contour shape chosen from energy_curve: "build" energy climbs
          then settles each phrase (arch), "fade" descends, riff mode
          ignores energy_curve and repeats a short 4-note ostinato cell
          instead of evolving.
        - ONE rhythmic motif is generated once (from the section's
          mid-point density, as a representative sample) and reused across
          every phrase, rather than resampling rhythm independently per
          bar — this is what actually makes it read as "composed" instead
          of aimless.
        This intentionally does not attempt full four-part species
        counterpoint or avoid all parallel motion with other voices —
        that's a much deeper feature; this is the phrase-and-contour layer.
        """
        if not progression:
            return []

        total_beats = bars * beats_per_bar
        key_pc = NOTE_MAP.get(key, 0)
        scale_intervals = SCALE_MODES.get(mode, SCALE_MODES["major"])
        scale = [(key_pc + iv) % 12 for iv in scale_intervals]  # ascending scale degrees, len 7 (or 8 for locrian etc.)
        n_degrees = len(scale)

        contour_name = "riff" if riff else _ENERGY_TO_CONTOUR.get(energy_curve, "arch")
        contour = _CONTOUR_TEMPLATES[contour_name]

        sample_density = density_curve[len(density_curve) // 2] if density_curve else 0.5
        subdivision = self._subdivision_for_density(sample_density)
        phrase_len_beats = min(total_beats, max(beats_per_bar * 2, beats_per_bar))
        motif_onsets = self._onset_grid(0, phrase_len_beats, subdivision)

        events: List[Dict[str, Any]] = []
        beat_cursor = 0.0
        phrase_idx = 0
        chord_idx = 0

        while beat_cursor < total_beats:
            while chord_idx < len(progression) - 1 and progression[chord_idx]["end_beat"] <= beat_cursor:
                chord_idx += 1
            chord = progression[chord_idx]
            root_pc = chord.get("root_pc", key_pc)
            tones = [(root_pc + iv) % 12 for iv in _chord_tones(chord.get("quality", ""))]

            # Riff mode repeats the identical cell every phrase (ostinato).
            # Lyrical modes advance one scale degree of "starting height"
            # per phrase, giving each repetition of the arch/ascend/descend
            # shape a sense of forward motion rather than looping in place.
            degree_offset = 0 if riff else phrase_idx

            for i, onset in enumerate(motif_onsets):
                start = beat_cursor + onset
                if start >= total_beats:
                    break
                contour_step = contour[i % len(contour)] + degree_offset
                scale_degree = contour_step % n_degrees
                octave_shift = contour_step // n_degrees
                pitch_class = scale[scale_degree]

                is_strong_beat = abs(onset - round(onset)) < 1e-6
                if is_strong_beat and tones and pitch_class not in tones:
                    pitch_class = min(tones, key=lambda t: min(abs(t - pitch_class), 12 - abs(t - pitch_class)))

                duration = subdivision
                if start + duration > total_beats:
                    duration = total_beats - start
                if duration <= 0:
                    continue

                events.append({
                    "start_beat": start, "duration_beats": duration,
                    "octave": 5 + octave_shift, "pitch_class": pitch_class,
                })

            beat_cursor += phrase_len_beats
            phrase_idx += 1

        return events

    def realize_section(self, section: Dict[str, Any]) -> List[Dict[str, Any]]:
        progression = section.get("progression", [])
        density_curve = section.get("density_curve", [])
        instruments = section.get("target_instruments", ["Piano"]) or ["Piano"]
        bars = max(1, section.get("bars", 1))
        beats_per_bar = section.get("beats_per_bar", 4) or 4
        # EXPLICIT MELODY: when present, the lead voice's notes come
        # entirely from the user's own melody instead of the algorithmic
        # density-driven subdivision — see the skip in the chord loop below
        # and the direct emission after it.
        melody_pattern = section.get("melody_pattern") or []
        if not melody_pattern:
            # No user-authored melody — generate one with real phrase
            # structure instead of falling back to old per-chord tone
            # cycling. If this returns empty (e.g. an empty progression),
            # the melody_pattern-skip check below naturally falls through
            # to the pre-existing per-chord lead behavior as a safety net.
            melody_pattern = self._generate_phrase_melody(
                progression, bars, beats_per_bar, density_curve,
                section.get("mood", "calm"), section.get("energy_curve", "build"),
                section.get("key", "C"), section.get("mode", "major"),
                riff=bool(section.get("riff_mode", False)),
            )

        resolved = []
        for idx, name in enumerate(instruments):
            # BUGFIX: "drum" in name.lower() alone missed "Percussion" —
            # get_program("Percussion") correctly returns 128 (the drum
            # sentinel), but that then went through
            # `min(program, self.max_instrument)` below, which clamps 128
            # down to 127 with default vocab sizes. GM program 127 is
            # "Gunshot" — every "Percussion" instrument in this whole
            # pipeline has been silently playing Gunshot instead of
            # routing to the drum channel. Checking the resolved program
            # value (>= DRUM_PROGRAM) instead of just the name substring
            # catches this regardless of what the instrument was called.
            is_drum_name = "drum" in name.lower() or "percussion" in name.lower()
            program = DRUM_PROGRAM if is_drum_name else get_program(name)
            if program >= DRUM_PROGRAM:
                program = DRUM_PROGRAM
            else:
                program = min(program, self.max_instrument)
            role = "lead" if idx == 0 else infer_role(program)
            resolved.append({"name": name, "program": program, "role": role})

        if len(resolved) > 1 and not any(r["role"] == "bass" for r in resolved):
            resolved[-1]["role"] = "bass"

        # SYMPHONIC MODE: give every harmony-role instrument a stable voice
        # index + the total harmony-voice count, so _realize_voice can
        # spread them across registers instead of stacking them in unison.
        harmony_voices = [r for r in resolved if r["role"] == "harmony"]
        for h_idx, r in enumerate(harmony_voices):
            r["_harmony_index"] = h_idx
            r["_harmony_total"] = len(harmony_voices)

        lead_voice = next((r for r in resolved if r["role"] == "lead"), None)
        # SOLO SUPPORT: when a solo_instrument was set, StructurePlanner
        # already moved it to index 0 (the "lead" role) — this section's
        # job is just to thin the backing (harmony) voices so the soloist
        # has room, the way a real rhythm section drops back for a solo.
        thin_harmony = bool(section.get("solo_instrument"))

        events: List[Dict[str, Any]] = []
        for chord in progression:
            root_pc = chord.get("root_pc", 0)
            # INVERSION SUPPORT: bass_override_pc is set by
            # StructurePlanner._parse_explicit_chord when a slash chord
            # (e.g. "F/A") was given. None for plain chords or anything
            # Markov-generated, in which case the bass just plays the root
            # as before.
            bass_override = chord.get("bass_override_pc")
            bass_pc = bass_override if bass_override is not None else root_pc
            tones = [(root_pc + iv) % 12 for iv in _chord_tones(chord.get("quality", ""))]
            tones = [min(t, self.max_pitch_class) for t in tones]

            start_beat = chord.get("start_beat", 0)
            end_beat = chord.get("end_beat", start_beat + beats_per_bar)
            chord_bars = self._bar_range(start_beat, end_beat, beats_per_bar)
            avg_density = self._avg_density(density_curve, chord_bars, bars)

            for voice in resolved:
                if melody_pattern and voice["role"] == "lead":
                    # Skip the algorithmic lead line entirely — the explicit
                    # melody below replaces it for the whole section, not
                    # per-chord-segment, since a user's melody doesn't need
                    # to phrase on chord boundaries.
                    continue
                events.extend(self._realize_voice(voice, tones, root_pc, bass_pc, start_beat, end_beat,
                                                   avg_density, thin_harmony))

        if melody_pattern and lead_voice is not None:
            for note in melody_pattern:
                events.append({
                    "start_beat": note["start_beat"], "instrument_name": lead_voice["name"],
                    "instrument_program": lead_voice["program"],
                    "octave": max(0, min(note["octave"], self.max_octave)),
                    "pitch_class": max(0, min(note["pitch_class"], self.max_pitch_class)),
                    # TIMING FORCING: duration_beats was already being computed
                    # by both explicit-melody parsing and _generate_phrase_melody
                    # but discarded here — carried through now so
                    # AgenticComposer can convert it into an actual forced
                    # duration token instead of leaving note length entirely
                    # up to the model.
                    "duration_beats": note.get("duration_beats", 1.0),
                    "role": "lead",
                })

        events.sort(key=lambda e: e["start_beat"])
        return events

    def _realize_voice(self, voice, tones, root_pc, bass_pc, start_beat, end_beat, density, thin_harmony=False):
        if voice["program"] == DRUM_PROGRAM:
            events = []
            duration_beats = int(end_beat - start_beat)
            for b in range(duration_beats):
                bar_beat = b % 4
                if bar_beat in (0, 2):
                    events.append({
                        "start_beat": start_beat + b, "instrument_name": voice["name"],
                        "instrument_program": voice["program"], "octave": 3, "pitch_class": 0,
                        "role": "drums", "duration_beats": 0.25,
                    })
                elif bar_beat in (1, 3):
                    events.append({
                        "start_beat": start_beat + b, "instrument_name": voice["name"],
                        "instrument_program": voice["program"], "octave": 3, "pitch_class": 2,
                        "role": "drums", "duration_beats": 0.25,
                    })
                
                if density >= 0.5:
                    events.append({
                        "start_beat": start_beat + b, "instrument_name": voice["name"],
                        "instrument_program": voice["program"], "octave": 3, "pitch_class": 6,
                        "role": "drums", "duration_beats": 0.25,
                    })
                    events.append({
                        "start_beat": start_beat + b + 0.5, "instrument_name": voice["name"],
                        "instrument_program": voice["program"], "octave": 3, "pitch_class": 6,
                        "role": "drums", "duration_beats": 0.25,
                    })
                else:
                    events.append({
                        "start_beat": start_beat + b, "instrument_name": voice["name"],
                        "instrument_program": voice["program"], "octave": 3, "pitch_class": 6,
                        "role": "drums", "duration_beats": 0.25,
                    })
            return events

        role = voice["role"]
        octave = min(default_octave_for_role(role), self.max_octave)
        duration_beats = max(1, int(end_beat - start_beat))

        if role == "bass":
            # DENSE QUEUE: Root on beat 1, Fifth on beat 3 (Standard Pop/Rock Groove)
            # INVERSION SUPPORT: when bass_pc differs from root_pc (a slash
            # chord like "F/A" was given), the specified bass note is
            # emphasized on the downbeat — where an inversion actually
            # matters musically — while the rest of the walking pattern
            # still alternates root/fifth around the chord's real harmonic
            # function, rather than trying to build a whole alternate
            # walking-bass pattern around the inversion note.
            events = []
            fifth_pc = (root_pc + 7) % 12
            for b in range(duration_beats):
                if b == 0 and bass_pc != root_pc:
                    pc = bass_pc
                else:
                    pc = root_pc if b % 2 == 0 else fifth_pc
                events.append({
                    "start_beat": start_beat + b, "instrument_name": voice["name"],
                    "instrument_program": voice["program"], "octave": max(0, octave - 1),
                    "pitch_class": min(pc, self.max_pitch_class), "role": "bass",
                    "duration_beats": 1.0,  # TIMING FORCING: each event holds one beat until the next alternation
                })
            return events

        if role == "harmony":
            harmony_total = voice.get("_harmony_total", 1)

            if harmony_total <= 1:
                # Single harmony voice: keep the original behavior — sustain
                # the full stacked voicing every beat. A lone piano/pad
                # carrying the whole chord is still the right call here;
                # there's nothing to spread across if there's only one part.
                # SOLO SUPPORT: when thinning for a soloist, drop to a
                # sparser 2-tone stack on every OTHER beat instead of a full
                # 4-tone stack every beat — opens up space instead of
                # competing with the featured voice.
                events = []
                step = 2 if thin_harmony else 1
                stack = tones[:2] if thin_harmony else tones[:4]
                for b in range(0, duration_beats, step):
                    for tone in stack:
                        events.append({
                            "start_beat": start_beat + b, "instrument_name": voice["name"],
                            "instrument_program": voice["program"], "octave": octave,
                            "pitch_class": min(tone, self.max_pitch_class), "role": "harmony",
                            "duration_beats": float(step),  # TIMING FORCING: holds until the next stack, `step` beats away
                        })
                return events

            # Multiple harmony voices: register-spread part-writing. Voice 0
            # (first harmony instrument in the section's instrument list —
            # typically the most prominent, e.g. first violins or soprano)
            # takes the highest listed chord tone; later voices step down
            # both which tone they play and which octave register they sit
            # in, so a Strings + French Horn + Choir "harmony" trio produces
            # three genuinely different, register-separated lines instead of
            # the same four notes three times over.
            # SOLO SUPPORT: odd-indexed harmony voices drop out entirely
            # when thinning for a soloist — half the backing steps back
            # rather than every voice playing at reduced volume, which
            # reads more like a real "band drops back for the solo" moment.
            h_idx = voice.get("_harmony_index", 0)
            if thin_harmony and h_idx % 2 == 1:
                return []

            tone_idx = (len(tones) - 1 - h_idx) % len(tones)
            voice_tone = tones[tone_idx]
            register_drop = h_idx // 2  # every 2 voices, drop one octave register
            voice_octave = max(0, min(octave - register_drop, self.max_octave))

            events = []
            for b in range(duration_beats):
                events.append({
                    "start_beat": start_beat + b, "instrument_name": voice["name"],
                    "instrument_program": voice["program"], "octave": voice_octave,
                    "pitch_class": voice_tone, "role": "harmony",
                    "duration_beats": 1.0,  # TIMING FORCING: one beat per sustained event
                })
            return events

        # role == "lead": rhythmic density decides subdivision. (This path
        # only runs when melody_pattern is empty — i.e. the phrase-melody
        # generator itself produced nothing, an edge case fallback; the
        # normal case is the lead voice being skipped here entirely and
        # emitted from melody_pattern instead, whether user-authored or
        # phrase-generated.)
        subdivision = self._subdivision_for_density(density)
        onsets = self._onset_grid(start_beat, duration_beats, subdivision)
        out = []
        for i, onset in enumerate(onsets):
            tone = tones[i % len(tones)]
            out.append({
                "start_beat": onset, "instrument_name": voice["name"],
                "instrument_program": voice["program"], "octave": octave,
                "pitch_class": min(tone, self.max_pitch_class), "role": "lead",
                "duration_beats": subdivision,  # TIMING FORCING: holds until the next onset in this grid
            })
        return out

    @staticmethod
    def _subdivision_for_density(density: float) -> float:
        if density < 0.35: return 4.0
        if density < 0.6: return 1.0
        if density < 0.8: return 0.5
        return 0.25

    @staticmethod
    def _onset_grid(start_beat: float, duration_beats: float, subdivision: float) -> List[float]:
        if duration_beats <= 0 or subdivision <= 0: return [start_beat]
        n = max(1, int(duration_beats / subdivision))
        return [start_beat + i * subdivision for i in range(n)]

    @staticmethod
    def _bar_range(start_beat: float, end_beat: float, beats_per_bar: int = 4):
        beats_per_bar = beats_per_bar or 4
        return int(start_beat // beats_per_bar), max(int(start_beat // beats_per_bar) + 1, int(end_beat // beats_per_bar))

    @staticmethod
    def _avg_density(density_curve: List[float], chord_bars, total_bars: int) -> float:
        if not density_curve: return 0.5
        lo, hi = chord_bars
        lo = max(0, min(lo, len(density_curve) - 1))
        hi = max(lo + 1, min(hi, len(density_curve)))
        window = density_curve[lo:hi] or [density_curve[-1]]
        return sum(window) / len(window)